### ISSUE TITLE
nats-streaming not able to connect with postgres sql store in docker compose

### ISSUE THREAD

**Issue by ehrktia** [nats-io/nats-streaming-server#1073]
Am starting with NATS streaming , as per documentation got a simple docker compose file as below.
```
version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres
        hostname: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
                - ./postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
                - ./data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    pgadmin:
          container_name: pgadmin
          image: dpage/pgadmin4
          depends_on:
            - postgres
          ports:
            - "80:80"
          environment:
              PGADMIN_DEFAULT_EMAIL: admin@admin.org
              PGADMIN_DEFAULT_PASSWORD: admin
          volumes:
            - $HOME/dt/msgbustest/pgadmin

    nats-streaming:
            image: nats-streaming
            container_name: nats
            environment:
              MESSAGE_BUS_USER: nats_client
              MESSAGE_BUS_PASS: nats_test
            command: --store SQL --sql_driver postgres --sql_source postgres://postgres:postgres@postgres?sslmode=disable
            ports:
                - "4222:4222"
                - "8222:8222"
            depends_on:
                        - postgres
networks:
    default:
        external:
            name: nats
```
i have created docker network nats using bridge default driver.
when i run docker-compose up -d command i get below logs.
```
Creating postgres ... done
Creating nats     ... done
Attaching to postgres, nats
nats              | [1] 2020/07/21 17:44:40.473838 [INF] STREAM: Starting nats-streaming-server[test-cluster] version 0.18.0
nats              | [1] 2020/07/21 17:44:40.473933 [INF] STREAM: ServerID: 9cjDgsxfM06AWnzgrP8DFE
nats              | [1] 2020/07/21 17:44:40.473936 [INF] STREAM: Go version: go1.14.4
nats              | [1] 2020/07/21 17:44:40.473938 [INF] STREAM: Git commit: [026e3a6]
nats              | [1] 2020/07/21 17:44:40.476213 [INF] STREAM: Shutting down.
nats              | [1] 2020/07/21 17:44:40.476228 [FTL] STREAM: Failed to start: dial tcp 172.27.0.2:5432: connect: connection refused
nats exited with code 1
postgres          |
postgres          | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres          |
postgres          | 2020-07-21 17:44:40.871 UTC [1] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres          | 2020-07-21 17:44:40.871 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres          | 2020-07-21 17:44:40.872 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres          | 2020-07-21 17:44:40.874 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres          | 2020-07-21 17:44:40.931 UTC [26] LOG:  database system was shut down at 2020-07-21 17:39:55 UTC
postgres          | 2020-07-21 17:44:40.956 UTC [1] LOG:  database system is ready to accept connections
```

If i start the nats with no persistance layer , it starts fine with no error.
FYI- i was working in linux and had same issue few months ago , but having it no more.
OS Details:
```
OSX
```
Please let me know if you require more details.
