### ISSUE TITLE
Authentication NATS Server

### ISSUE THREAD

**Issue by AndreasM009** [nats-io/nats-streaming-server#1123]
I have setup a NATS Server with token authentication. Does the NATS Streaming operator support token authentication to authenticate to the NATS Server?

**Comment by kozlovic** [comment]
Not sure about the operator. The streaming server only supports the use of a token to authenticate since the last version v0.19.0 (https://github.com/nats-io/nats-streaming-server/pull/1100).

Checking with @wallyqs who is maintaining the operator.

**Comment by AndreasM009** [comment]
@kozlovic what I did is the following. I set up a NATS cluster with NATS operator and configured authentication using a Kubernetes Secret from file:
```json
{
    "token": "mytoken",
    "default_permissions": {
        "publish": [">"],
        "subscribe": [">"]
      }
}
```

This works fine as the Secret is referenced in NatsCuster CRD:

```yaml
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "my-nats"
spec:
  size: 2
  auth:
    clientsAuthSecret: "nats-client-auth"
    clientsAuthTimeout: 5
```

This results in the expected behaviour, the token mus be used to authenticate clients.
But when I setup a NatsStreamingCluster resource and mount the following config file from a Kuberenetes Secret I get ant authentication violation in the streaming server:
```txt
streaming: {
    token: "mytoken"
}
```

Is the configuration file for the streaming server correct?
It only works if I specify the token in the `natsSvc` property like that:

```yaml
...
spec:
  natsSvc: "token@my-nats"
```
