### ISSUE TITLE
All(3) nats-streaming instances start as "stand-by" mode and never become "active"

### ISSUE THREAD

**Issue by FlightToFreedom** [nats-io/nats-streaming-server#1222]
Hello, 
I am running 3 nats server pods with a service connected to them, and 3 nats-streaming instances in kubernetes cluster.
The nats-streaming connect to the nats server via the nats's service
Although all components run fine, the 3 nats-streaming instances all start as "stand-by" and remains as such.
Eventually the status wont change, where i would expect one of the three nats-streaming instances to log something like:
```
[35] 2021/09/30 08:00:27.565273 [INF] STREAM: Starting in standby mode
**[35] 2021/09/30 08:00:28.909457 [INF] STREAM: Server is active**
[35] 2021/09/30 08:00:29.568671 [INF] STREAM: Message store is FILE
[35] 2021/09/30 08:00:29.568693 [INF] STREAM: Store location: /data
[35] 2021/09/30 08:00:29.568815 [INF] STREAM: ---------- Store Limits ----------
[35] 2021/09/30 08:00:29.568832 [INF] STREAM: Channels:                  100 *
[35] 2021/09/30 08:00:29.568838 [INF] STREAM: --------- Channels Limits --------
[35] 2021/09/30 08:00:29.568842 [INF] STREAM:   Subscriptions:          1000 *
[35] 2021/09/30 08:00:29.568846 [INF] STREAM:   Messages     :       1000000 *
[35] 2021/09/30 08:00:29.568850 [INF] STREAM:   Bytes        :     976.56 MB *
[35] 2021/09/30 08:00:29.568854 [INF] STREAM:   Age          :       72h0m0s
[35] 2021/09/30 08:00:29.568858 [INF] STREAM:   Inactivity   :     unlimited *
[35] 2021/09/30 08:00:29.568872 [INF] STREAM: ----------------------------------
[35] 2021/09/30 08:00:29.568877 [INF] STREAM: Streaming Server is ready

```
I cant figure out where the problem is, i have also added the `-DV` option on the nats streaming in the hope that it would log some additional infos but nothing, all i see on all instances is:

```
[7] 2021/11/11 12:12:01.727327 [INF] STREAM: Starting nats-streaming-server[build] version 0.10.2
[7] 2021/11/11 12:12:01.727379 [INF] STREAM: ServerID: DRXa22vl2pehQdIWbPs1qn
[7] 2021/11/11 12:12:01.727386 [INF] STREAM: Go version: go1.10.3
[7] 2021/11/11 12:12:01.756291 [INF] STREAM: Starting in standby mode
```
From [this](https://docs.nats.io/nats-streaming-concepts/ft/active-server) page of the official doc, i see that 
`If the elected server fails to grab this lock because it is already locked, it will go back to standby.`
I use FileStore implementation and the directory created by nats-streaming ('/data' in my case) is empty. 

Here is my setup:
Nats server and service:

```
apiVersion: v1
kind: Service
metadata:
  namespace: one-test
  name: nats
  labels:
    app: nats
spec:
  clusterIP: None
  ports:
  - port: 4222
    targetPort: 4222
    name: nats
  - port: 6222
    targetPort: 6222
    name: route
  - port: 8222
    targetPort: 8222
    name: web
  selector:
    app: nats

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: one-test
  name: nats
spec:
  replicas: 3
  serviceName: nats
  template:
    metadata:
      namespace: one-test
      name: nats
      labels:
        app: nats
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "7777"
        prometheus.io/scrape: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nats
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nats
        image: docker.io/library/nats:1.2.0-linux
        args:
        - -p
        - '4222'
        - -m
        - '8222'
        - -cluster
        - nats://0.0.0.0:6222
        - -routes
        - nats://nats-0.nats.one-test.svc.orca.local:6222,nats://nats-1.nats.one-test.svc.orca.local:6222,nats://nats-2.nats.one-test.svc.orca.local:6222
        ports:
        - containerPort: 4222
        - containerPort: 8222
        - containerPort: 6222
      - name: metrics
        image: appcelerator/prometheus-nats-exporter
        args:
        - -subz
        - -connz
        - -routez
        - -varz
        - -p
        - '7777'
        - http://localhost:8222
        ports:
        - containerPort: 7777
```
Nats streaming:

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: one-test
  name: nats-streaming
spec:
  serviceName: nats-streaming
  replicas: 3
  template:
    metadata:
      namespace: one-test
      name: nats-streaming
      labels:
        app: nats-streaming
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nats-streaming
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nats
        image: docker.io/library/nats-streaming:0.10.2-linux
        args:
        - --nats_server
        - nats://nats.one-test.svc:4222
        - -DV
        - --cluster_id
        - build
        - --store
        - FILE
        - --dir
        - /data
        - -m
        - '8222'
        - --max_age
        - 72h
        - -ft_group
        - ft
        ports:
        - containerPort: 8222
        volumeMounts:
        - name: data
          mountPath: /data
      nodeSelector:
        type: production
      tolerations:
      - key: dedicated
        value: dev2
        effect: NoSchedule
      volumes:
      - name: data
        hostPath:
          path: /org/nfs/one-test/nats-streaming/data
```

Note that since is a fresh intallation the path:  '/org/nfs/one-test/nats-streaming/data' has been created by NATS successfully and is empty.
also note, since i dont know what "lock" in NATS terms means, i have checked the locks on the host machine of the datastore and i see no locks:
```
COMMAND         PID   TYPE SIZE MODE  M START END PATH
(unknown)        -1 OFDLCK   0B READ  0     0   0
(unknown)        -1 OFDLCK   0B READ  0     0   0
```

Nats servers are up and running:
```
[7] 2021/11/11 11:41:58.444959 [INF] Starting nats-server version 1.2.0
[7] 2021/11/11 11:41:58.445029 [INF] Git commit [6608e9a]
[7] 2021/11/11 11:41:58.445369 [INF] Starting http monitor on 0.0.0.0:8222
[7] 2021/11/11 11:41:58.445444 [INF] Listening for client connections on 0.0.0.0:4222
[7] 2021/11/11 11:41:58.445469 [INF] Server is ready
[7] 2021/11/11 11:41:58.446239 [INF] Listening for route connections on 0.0.0.0:6222
[7] 2021/11/11 11:41:58.447992 [INF] 10.254.64.3:6222 - rid:1 - Route connection created
[7] 2021/11/11 11:41:58.448614 [INF] 10.254.64.3:55332 - rid:2 - Route connection created
[7] 2021/11/11 11:41:58.449364 [INF] 10.254.70.2:6222 - rid:3 - Route connection created
[7] 2021/11/11 11:41:58.449630 [INF] 10.254.19.7:6222 - rid:4 - Route connection created
[7] 2021/11/11 11:42:00.961556 [INF] 10.254.70.0:46032 - rid:5 - Route connection created
[7] 2021/11/11 11:42:01.416831 [INF] 10.254.19.0:47442 - rid:6 - Route connection created
```
