### ISSUE TITLE
nats streaming redelivers delivered messages

### ISSUE THREAD

**Issue by yavuzyurtbegendi** [nats-io/nats-streaming-server#665]
```  
nats:
    image: nats-streaming:latest
    restart: always
    command: ["--store", "file", "--dir", "./data", "-auth", "${AUTH}"]
    volumes:
      - ./data/nats:/data
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
```
I also tried, `./data`, `/data`, `data` as a directory, with different combinations

1. After delivering messages, I acknowledge the messages
2. I shutdown docker-compose with `docker-compose down`, after closing docker,
3. I run,  `docker-compose up` and I see messages redelivered again and sometimes they are not redelivered, can you help me to fix this issue
