### ISSUE TITLE
Failed to start: unable to prepare statement "SELECT id, tick from StoreLock FOR UPDATE": pq: relation "storelock" does not exist

### ISSUE THREAD

**Issue by wallyqs** [nats-io/nats-streaming-server#856]
To reproduce:

```sh
$ docker run -d -e POSTGRES_PASSWORD=password -p 5432:5432 postgres
$ docker run -p 4222:4222 -p 8222:32768 nats-streaming -SDV --store sql --sql_driver postgres --sql_source="user=postgres password=password host=172.17.0.1 port=5432 sslmode=disable"
[1] 2019/06/06 23:38:07.114537 [INF] STREAM: Starting nats-streaming-server[test-cluster] version 0.14.3
[1] 2019/06/06 23:38:07.114624 [INF] STREAM: ServerID: m9dlqjIAfXMxVp8rmk7NuU
[1] 2019/06/06 23:38:07.114647 [INF] STREAM: Go version: go1.11.10
[1] 2019/06/06 23:38:07.114665 [INF] STREAM: Git commit: [1ce7677]
[1] 2019/06/06 23:38:07.124341 [INF] STREAM: Shutting down.
[1] 2019/06/06 23:38:07.124426 [FTL] STREAM: Failed to start: unable to prepare statement "SELECT id, tick from StoreLock FOR UPDATE": pq: relation "storelock" does not exist
```

**Comment by wallyqs** [comment]
This can be solved by initializing the postgres DB: 

```
ID=$(docker run -d -e POSTGRES_PASSWORD=password -p 5432:5432 postgres)
cat postgres.db.sql | docker exec -i $ID psql -h 127.0.1.1 -U postgres
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE TABLE
ALTER TABLE

$ docker run -p 4222:4222 -p 8222:32768 nats-streaming -SDV --store sql --sql_driver postgres --sql_source="user=postgres password=password host=172.17.0.1 port=5432 sslmode=disable"
```

**Comment by heartwilltell** [comment]
Failed to start: unable to prepare statement "INSERT INTO Clients (id, hbinbox, proto) VALUES ($1, $2, $3)": pq: column "proto" of relation "clients" does not exist

**Comment by kozlovic** [comment]
@heartwilltell Not sure what you are asking here. The script does ALTER the table to add this column. This column was added at some point and the script was modified to do ALTER so that people could use it to upgrade their existing tables.

**Comment by kozlovic** [comment]
@msrumon I don't have an answer for that one, but I would say that this script should not be running as the normal step of starting the nats-streaming-server. The script should be run only once (or when the script is modified to alter the database, which happened only once so far) and should be run by the database administrator.

**Comment by msrumon** [comment]
> @msrumon I don't have an answer for that one, but I would say that this script should not be running as the normal step of starting the nats-streaming-server. The script should be run only once (or when the script is modified to alter the database, which happened only once so far) and should be run by the database administrator.

Got it. Thanks for the clarification.

**Comment by saikarthikp9** [comment]
I got this error as well. I am using docker-compose and running a new instance of postgres. 

docker-compose
```
version: '3.7'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - '.env'
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
  # TODO: eventually make this a cluster
  nats:
    image: nats-streaming
    command:
      - '--port'
      - '4222'
      - '--http_port' #monitoring
      - '8222'
      - '--hb_interval' #heartbeat
      - '5s'
      - '--hb_timeout'
      - '5s'
      - '--hb_fail_count'
      - '2'
      - '--stan_debug' # TODO: remove in prod, too verbose so will affect performance
      - '--cluster_id'
      - 'restaurant'
      - '--store'
      - 'sql'
      - '--sql_driver'
      - 'postgres'
      - '--sql_source'
      - 'user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} host=${POSTGRES_URL} port=${POSTGRES_PORT} dbname=${POSTGRES_DB} sslmode=disable'
      # - '--sql_no_caching'
    restart: always
    ports:
      - 4222:4222 # client
      - 8222:8222 # monitoring
    links:
      - db
    depends_on: 
      - db
```

logs
```
[1] 2021/10/14 01:48:57.788921 [INF] STREAM: Starting nats-streaming-server[restaurant] version 0.22.1
[1] 2021/10/14 01:48:57.789052 [INF] STREAM: ServerID: 0JDFFo1TPD4vWqEgM6Gn6x
[1] 2021/10/14 01:48:57.789064 [INF] STREAM: Go version: go1.16.6
[1] 2021/10/14 01:48:57.789076 [INF] STREAM: Git commit: [27f1d60]
[1] 2021/10/14 01:48:57.810851 [FTL] STREAM: Failed to start: unable to prepare statement "SELECT id, tick from StoreLock FOR UPDATE": pq: relation "storelock" does not exist
```
any ideas?
