### ISSUE TITLE
STREAM: Failed to start: file store should not be opened consecutively with the TruncateUnexpectedEOF option set to true

### ISSUE THREAD

**Issue by lrh3321** [nats-io/nats-streaming-server#895]
running docker image with docker-compose

```yaml
version: '3'
services:
  nats-streaming:
    image: nats-streaming
    container_name: nats-streaming
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-m", "8222", "-store", "file", "-dir", "datastore", "--file_truncate_bad_eof"]
```

then

```bash
docker-compose up -d nats-streaming
docker-compose restart nats-streaming
```

https://github.com/nats-io/nats-streaming-server/blob/3625a0b784aa7e19df3892517f2c07ebb894c152/stores/filestore.go#L1290-L1303

I think should store and check pid in the truncateBadEOFFileName
