### ISSUE TITLE
Unable to add RootCA for connection to external NATS Server from NATS Streaming 0.14.3, 0.15.x, and 0.16.x

### ISSUE THREAD

**Issue by Starefossen** [nats-io/nats-streaming-server#919]
We have a setup where we have a 3 nodes NATS Server cluster  and a 3 nodes NATS Streaming cluster that are independent of each other. NATS Server is secured by TLS and user token authentication using the NATS Server Operator.

Our NATS Server is crrently running running version `v1.4.1` and we are in the process of upgrading to `v2.0.4` but before we can so we need to upgrade NATS Streaming first.

The first thing we realized when we upgraded was that host name verification is now enforced since the merge of https://github.com/nats-io/nats.go/pull/420 and we got the following error:

```
[1] 2019/08/20 10:37:45.003137 [INF] STREAM: Starting nats-streaming-server[stan-tls-cluster] version 0.16.0                                                                                                                                                                                                                  
[1] 2019/08/20 10:37:45.003187 [INF] STREAM: ServerID: t3uswlfx0H0hmfJee7wfFF                                                                                  
[1] 2019/08/20 10:37:45.003194 [INF] STREAM: Go version: go1.11.13                                                                                             
[1] 2019/08/20 10:37:45.003198 [INF] STREAM: Git commit: [27593aa]                                                                                             
[1] 2019/08/20 10:37:45.049665 [INF] STREAM: Shutting down.                                                                                                    
[1] 2019/08/20 10:37:45.049978 [FTL] STREAM: Failed to start: x509: certificate signed by unknown authority                                                    
```

When consulting the NATS Streaming docs regarding TLS for NATS Streaming as well as the source code we are confident that the `-tls_client_cacert` is the correct configuration. 

https://github.com/nats-io/nats-streaming-server/blob/d9c28b60891f04891ae64093fe770e9e34437c81/server/server.go#L1441-L1445

However, once setting this flag in 0.14.3, 0.15.1 and 0.16.0 produces the following error and NATS Streaming imediately shuts down:

```
TLS Server certificate must be present and valid
```

The only reference I can find to this error is from the nats-server (keep in mind that I see this from my nats-streaming server that is configured to use an external NATS cluster and not the embedded one):

https://github.com/nats-io/nats-server/blob/e76f66c1cd07da296a314bcd1bfee9477918e596/server/opts.go#L2861-L2866

This leads me to believe that my NATS Streaming server now tries to start the embedded NATS Server and that I might have the incorrect config for how to set the CA Cert.

This is my full NATS Streaming pod specification for Kubernetes:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nats-streaming
    chart: nats-streaming-0.6.3
    release: stan-tls-cluster
  name: stan-tls-cluster-nats-streaming-0
  namespace: nats
spec:
  containers:
  - args:
    - -clustered
    - -cid
    - stan-tls-cluster
    - -m
    - "8222"
    - -ns
    - nats://nats-cluster:4222
    - -mc
    - "100"
    - -msu
    - "1000"
    - -mm
    - "1000000"
    - -mb
    - 900mb
    - -ma
    - "0"
    - -mi
    - 604800s
    - -hbi
    - 30s
    - -hbt
    - 10s
    - -hbf
    - "330"
    - --cluster_node_id
    - $(POD_NAME)
    - --cluster_peers
    - stan-tls-cluster-nats-streaming-0,stan-tls-cluster-nats-streaming-1,stan-tls-cluster-nats-streaming-2
    - --store
    - file
    - --dir
    - /nats/stan-tls-cluster/$(POD_NAME)/data
    - --cluster_log_path
    - /nats/stan-tls-cluster/$(POD_NAME)/raft
    - --cluster_raft_logging
    - --file_compact_enabled
    - --file_compact_frag
    - "50"
    - --file_compact_interval
    - "300"
    - --file_compact_min_size
    - "1048576"
    - --file_buffer_size
    - "2097152"
    - --file_crc
    - --file_crc_poly
    - "3988292384"
    - --file_sync
    - --file_slice_max_msgs
    - "0"
    - --file_slice_max_bytes
    - "67108931"
    - --file_slice_max_age
    - "0"
    - --file_fds_limit
    - "0"
    - --file_parallel_recovery
    - "1"
    - -tls_client_cacert
    - /var/secrets/nats-streaming-tls/ca.pem
    - --user
    - $(USER)
    - --pass
    - $(PASSWORD)
    - -SD
    - -SV
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: USER
      value: stan-tls-cluster-nats-streaming
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          key: token
          name: stan-tls-cluster-nats-streaming-nats-cluster-bound-token
    image: docker.io/nats-streaming:0.16.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 6
      httpGet:
        path: /
        port: monitoring
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: nats-streaming
    ports:
    - containerPort: 8222
      name: monitoring
      protocol: TCP
    readinessProbe:
      failureThreshold: 6
      httpGet:
        path: /
        port: monitoring
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /nats
      name: datadir
    - mountPath: /var/secrets/nats-streaming-tls
      name: nats-streaming-tls
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-ktf5q
      readOnly: true
  - args:
    - -serverz
    - -channelz
    - -connz
    - -routez
    - -subz
    - -varz
    - http://localhost:8222
    image: docker.io/synadia/prometheus-nats-exporter:0.5.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: metrics
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: metrics
    ports:
    - containerPort: 7777
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: metrics
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-ktf5q
      readOnly: true
  dnsPolicy: ClusterFirst
  hostname: stan-tls-cluster-nats-streaming-0
  nodeName: gke-apps-apps-workers-2a1fcb77-3x81
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: datadir
    persistentVolumeClaim:
      claimName: datadir-stan-tls-cluster-nats-streaming-0
  - name: nats-streaming-tls
    secret:
      defaultMode: 420
      secretName: nats-streaming-tls
  - name: default-token-ktf5q
    secret:
      defaultMode: 420
      secretName: default-token-ktf5q
```
