### ISSUE TITLE
Very low performance in FILE store

### ISSUE THREAD

**Issue by powerman** [nats-io/nats-streaming-server#968]
Comparing to https://github.com/nats-io/nats-streaming-server/issues/899 I see much worse FILE store performance, and I wonder is it normal or there is some regression?

Here is my docker-compose.yml:
```yaml
version: "3.7"
services:
    nats:
        image: "nats:2.1.0"
        restart: always
        ports:
            - "14222:4222"

    stan:
        image: "nats-streaming:0.16.2"
        restart: always
        volumes:
            - "./stan:/data"
        command:
            - "--cluster_id=devenv"
            - "--nats_server=nats://nats:4222"
            - "--store=FILE"
            - "--dir=/data"
```

Results (2nd run is more adequate because subscriber isn't blocked by publisher this time, so we see real publishing rate which is less than 100/s):
```
$ stan-bench -s nats://127.0.0.1:14222 -c devenv -id bench -n 1000 -ms 1024 -np 1 -ns 1 bench                                                                        
Starting benchmark [msgs=1000, msgsize=1024, pubs=1, subs=1]
NATS Streaming Pub/Sub stats: 106 msgs/sec ~ 106.32 KB/sec
 Pub stats: 53 msgs/sec ~ 53.16 KB/sec
 Sub stats: 53 msgs/sec ~ 53.21 KB/sec
$ stan-bench -s nats://127.0.0.1:14222 -c devenv -id bench -n 1000 -ms 1024 -np 1 -ns 1 bench
Starting benchmark [msgs=1000, msgsize=1024, pubs=1, subs=1]
NATS Streaming Pub/Sub stats: 193 msgs/sec ~ 193.65 KB/sec
 Pub stats: 96 msgs/sec ~ 96.78 KB/sec
 Sub stats: 62,972 msgs/sec ~ 61.50 MB/sec
```
If we add extra options `--file_sync=false --file_auto_sync=1ms` publishing speed increases a lot (up to 5000 - see second run), but it's still much lower than in issue referenced above (65,580 msgs/sec):
```
$ stan-bench -s nats://127.0.0.1:14222 -c devenv -id bench -n 10000 -ms 1024 -np 1 -ns 1 bench2                                                                      
Starting benchmark [msgs=10000, msgsize=1024, pubs=1, subs=1]
NATS Streaming Pub/Sub stats: 4,487 msgs/sec ~ 4.38 MB/sec
 Pub stats: 2,243 msgs/sec ~ 2.19 MB/sec
 Sub stats: 2,244 msgs/sec ~ 2.19 MB/sec
$ stan-bench -s nats://127.0.0.1:14222 -c devenv -id bench -n 10000 -ms 1024 -np 1 -ns 1 bench2
Starting benchmark [msgs=10000, msgsize=1024, pubs=1, subs=1]
NATS Streaming Pub/Sub stats: 10,191 msgs/sec ~ 9.95 MB/sec
 Pub stats: 5,095 msgs/sec ~ 4.98 MB/sec
 Sub stats: 27,659 msgs/sec ~ 27.01 MB/sec
```
I belive my hardware is no worse (actually I suppose it's better) than Mac used in referenced tests: I've i7-2600K overclocked to 4.5GHz, 24 GB RAM, SSD.

**Comment by powerman** [comment]
SQL store (postgres) benchmarks shows (1.5-4 times) higher numbers than FILE store.

Changes in docker-compose.yml:
```yaml
    stan-postgres:
        image: "postgres:11.5"
        restart: always
        volumes:
            - {type: "tmpfs", target: "/dev/shm", tmpfs: {size: 268435456}}
            - "stan-postgres:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER:                      user
            POSTGRES_PASSWORD:                  pass
            POSTGRES_DB:                        stan

    stan:
        image: "nats-streaming:0.16.2"
        restart: always
        command:
            - "--cluster_id=devenv"
            - "--nats_server=nats://nats:4222"
            - "--store=SQL"
            - "--sql_driver=postgres"
            - "--sql_source=postgres://user:pass@stan-postgres/stan?sslmode=disable"
            - "--sql_no_caching=true"
            - "--sql_max_open_conns=95" # of 100 (postgres default AFAIR)
```
Results:
```
$ stan-bench -s nats://127.0.0.1:14222 -c devenv -id bench -n 1000 -ms 1024 -np 1 -ns 1 bench                                                                         
Starting benchmark [msgs=1000, msgsize=1024, pubs=1, subs=1]
NATS Streaming Pub/Sub stats: 293 msgs/sec ~ 293.24 KB/sec
 Pub stats: 146 msgs/sec ~ 146.62 KB/sec
 Sub stats: 146 msgs/sec ~ 146.69 KB/sec
$ stan-bench -s nats://127.0.0.1:14222 -c devenv -id bench -n 1000 -ms 1024 -np 1 -ns 1 bench
Starting benchmark [msgs=1000, msgsize=1024, pubs=1, subs=1]
NATS Streaming Pub/Sub stats: 329 msgs/sec ~ 329.32 KB/sec
 Pub stats: 164 msgs/sec ~ 164.77 KB/sec
 Sub stats: 556 msgs/sec ~ 556.82 KB/sec
```
and now with `--sql_no_caching=false`:
```
$ stan-bench -s nats://127.0.0.1:14222 -c devenv -id bench -n 1000 -ms 1024 -np 1 -ns 1 bench2
Starting benchmark [msgs=1000, msgsize=1024, pubs=1, subs=1]
NATS Streaming Pub/Sub stats: 378 msgs/sec ~ 378.72 KB/sec
 Pub stats: 189 msgs/sec ~ 189.36 KB/sec
 Sub stats: 189 msgs/sec ~ 189.52 KB/sec
$ stan-bench -s nats://127.0.0.1:14222 -c devenv -id bench -n 1000 -ms 1024 -np 1 -ns 1 bench2
Starting benchmark [msgs=1000, msgsize=1024, pubs=1, subs=1]
NATS Streaming Pub/Sub stats: 814 msgs/sec ~ 814.26 KB/sec
 Pub stats: 407 msgs/sec ~ 407.46 KB/sec
 Sub stats: 9,977 msgs/sec ~ 9.74 MB/sec
```
