### ISSUE TITLE
could not setup cluster in k8s

### ISSUE THREAD

**Issue by ljfuyuan** [nats-io/nats-streaming-server#983]
Hi,here is my .yaml for setup cluster with 3 nodes in k8s
But, I alawys get the same error about "streaming state was recovered but cluster log path "/datastore/raft-*" is empty" , Even i remove all data or directory and set the "--cluster_log_path" first, is there something wrong with my config?  

btw, i use the Clustering Auto Configuration,and k8s service which named "nats-streaming-svc", the svc contains three nodes ip.

when i setup the cluaster, the first one node will be ok, and the others always faild with the error and the log said there is something Recovered,but i am sure ,i delete all data before this.

> [1] 2019/12/05 05:05:52.086025 [INF] STREAM: Recovering the state...
> [1] 2019/12/05 05:05:52.141745 [INF] STREAM: Recovered 0 channel(s)

the node-1
```
        image: nats-streaming:0.16.2-linux
        args: [ "-cid=nats-cluster","--cluster_node_id=nats-1","-mc=1000","-st=FILE","--dir=/datastore/nats-1","--clustered=true","--cluster_log_path=/datastore/raft-1","--routes=nats://nats-streaming-svc:6222","--cluster=nats://0.0.0.0:6222,"--cluster_bootstrap=true"]
        volumeMounts:
          - name: data-volume
            mountPath: /datastore
            subPath: nats-data
```

the node-2
```
        image: nats-streaming:0.16.2-linux
        args: [ "-cid=nats-cluster","--cluster_node_id=nats-2","-mc=1000","-st=FILE","--dir=/datastore/nats-2","--clustered=true","--cluster_log_path=/datastore/raft-2","--routes=nats://nats-streaming-svc:6222","--cluster=nats://0.0.0.0:6222"]
        volumeMounts:
          - name: data-volume
            mountPath: /datastore
            subPath: nats-data
```

and the node-3
```
        image: nats-streaming:0.16.2-linux
        args: [ "-cid=nats-cluster","--cluster_node_id=nats-3","-mc=1000","-st=FILE","--dir=/datastore/nats-3","--clustered=true","--cluster_log_path=/datastore/raft-3","--routes=nats://nats-streaming-svc:6222","--cluster=nats://0.0.0.0:6222"]
        volumeMounts:
          - name: data-volume
            mountPath: /datastore
            subPath: nats-data
```
